### ISSUE TITLE
Bootable subleq eForth

### ISSUE THREAD

**Issue by pbrochard** [howerj/subleq#1]
Hi, as an exercice to port a more complete colorForth to bare metal x86, I managed to embed (really easily) and boot subleq eForth in qemu-x86.

The embedded version is here: https://github.com/pbrochard/subleq/tree/subleq-eForthOS/embed (not very interesting but it was the first step before booting subleq eForth).

The bootable version is here: https://github.com/pbrochard/subleq/tree/subleq-eForthOS/boot

It's more an assembler exercice than a subleq/eForth one.
Feel free to ask for or create a pull request if you think it's valuable (same licence as subleq eForth).

Many many thanks for your book. It's pure poetry!

**Comment by howerj** [comment]
Thanks for this!

I'm moving house at the moment and have managed to steal only a few minutes to look at this, so I won't be able to do much for a while, but I did manage to get it running. It's really cool!

I'll either merge it, or perhaps make another project for it? I've made a bunch of "subleq-{language}" repos, although it seems weird me hosting it as you've done all the work. I could perhaps link to it in the "readme.md" if you did setup the repo?

Thanks again for this.

**Comment by pbrochard** [comment]
Hi, I have polished it a little and made the pull request. Feel free to merge it. 
I have just used **your hard work** and the one of others.
I think, as a reader, I would have liked to have the asm code to boot. It's too funny.
Also I think that the subleq vm is one of the easiest to port. We have a full forth with less than 600 asm bytes (and it's not hardcore asm).
Indeed if you prefer to have this work in a separate place, I can setup a repo for it.
Also the boot part depends on `subleq.dec`. It's maybe a waste to duplicate it in another repo.

**Comment by howerj** [comment]
I think I'd prefer it in a separate repository, as that's what I've done for my [Python](https://github.com/howerj/subleq-python), [Perl](https://github.com/howerj/subleq-perl), [JavaScript](https://github.com/howerj/subleq-js) and [Forth](https://github.com/howerj/subleq-forth) implementations of the SUBLEQ VM, they all include a `subleq.dec` file which I sometimes update. I did that to keep the repository nice and simple.

I might merge the pull request and then remove it so it appears in the history though.

**Comment by howerj** [comment]
Also of note, for those languages I've added a much larger image that includes floating point words, a better decompiler, and more control structures as well, which might be useful

**Comment by pbrochard** [comment]
Ok, no problem. I'll setup the repo this days. Also this way I'll not bother you if it needs some updates.
(I want to add an automatic keyboard mapping generation. And a grub entry to boot on a real hardware.)
I'll tell you once it's done.

**Comment by howerj** [comment]
That's great! Thanks!

**Comment by pbrochard** [comment]
Hi, the repo is up here: https://github.com/pbrochard/subleq-eForthOS
I have added the FR mapping generated with `subleq-eForth` itself :grin: 
And also the `grub2` configuration to boot it on a real hardware.
Best regards.

**Comment by howerj** [comment]
That's great work! I'll close this then, thanks for making that repo. I've added a link to the `readme.md` file.

**Comment by pbrochard** [comment]
Great! Thanks a lot!
